#!/usr/bin/bash

_qtile() {
    cmd="$1"

    case "$cmd" in
        "togroup"   ) qtile cmd-obj -o group "$2" -f toscreen  ;;
        "setlayout" ) qtile cmd-obj -o group -f setlayout -a "$2" ;;
    esac
}

wm="$1"; shift
case "$wm" in
    qtile ) _qtile "$@" 
esac    

