[tool.pyright]
pythonPlatform = "Linux"

reportAny = false
reportExplicitAny = false
reportIgnoreCommentWithoutRule = false
reportImplicitRelativeImport = false
reportMissingTypeArgument = false
reportMissingParameterType = false
reportUnknownArgumentType = false
reportUnknownLambdaType = false
reportUnknownMemberType = false
reportUnknownParameterType = false
reportUnknownVariableType = false


[tool.ruff.lint]
ignore = [

]

