#!/usr/bin/bash

# calendar() {
#     grep "calendar" <<< "$(eww active-windows)" \
#         && { eww close calendar && eww update cal-reveal="false" ; } \
#         || { eww open calendar  && eww update cal-reveal="true"  ; }
# }
#
# case $1 in
#     "calendar" ) calendar ;; 
# esac

grep "$1" <<< "$(eww active-windows)" \
    && { eww close "$1" && eww update "${1}-reveal"="false" ; } \
    || { eww open "$1" && eww update "${1}-reveal"="true" ; }
