#!/bin/bash

_qtile() {
    cmd="$1"; shift

    case "$cmd" in
        "togroup" ) qtile cmd-obj -o group $1 -f toscreen ;;
    esac
}

wm="$1"; shift

case "$wm" in
    qtile ) _qtile "$@" 
esac    

