#!/usr/bin/env zsh
# vim: set filetype=bash:

p10k_init() {
    # Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.config/.zsh/.zshrc.
    # Initialization code that may require console input (password prompts, [y/n]
    # confirmations, etc.) must go above this block; everything else may go below.
    if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
        source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
    fi
}

p10k_setup() {
    source ~/.local/software/git/powerlevel10k/powerlevel10k.zsh-theme
    [[ -f "$ZDOTDIR/plugins/p10k.zsh" ]] && source "$ZDOTDIR/plugins/p10k.zsh"
}

case "$1" in
    "init"  ) p10k_init "$@"  ;;
    "setup" ) p10k_setup "$@" ;;
    * ) echo "zsh plugins/.p10k - Unknown command "$1""
esac

unfunction p10k_init p10k_setup
