-- return {
--     { import = "plugins.theme" },
--     { import = "plugins.ui" },
--     { import = "plugins.coding" },
--     { import = "plugins.utility" },
--     { import = "plugins.lsp" },
--     { import = "plugins.langs" },
--     { import = "plugins.apps" },
-- }
