return { 
    "nvim-treesitter/nvim-treesitter",
    build = ":TSUpdate",
    config = function()
        local configs = require("nvim-treesitter.configs")
        
        configs.setup({
            ensure_installed = {
                "bash", 
                "c", 
                "cmake",
                "commonlisp", 
                "cpp",
                "css",
                "csv",
                "dockerfile",
                "fennel",
                "git_config",
                "git_rebase",
                "gitattributes",
                "gitcommit",
                "gitignore",
                "go",
                "gpg",
                "html",
                "ini",
                "java",
                "javascript", 
                "jq",
                "json",
                "json5",
                "latex",
                "lua", 
                "make",
                "markdown",
                "markdown_inline",
                "python",
                "passwd",
                "pem",
                "rasi",
                "rust",
                "sql",
                "ssh_config",
                "sxhkdrc",
                "toml",
                "vim",
                "vimdoc",
                "xml",
                "yaml",
                "yuck",
            },
            highlight = { enable = true },
            indent = { enable = true},
        })
    end
}
